spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/async_test
    username: root2
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false